language: python
dist: xenial
matrix:
  include:
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'

before_install:
  - python3 --version

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade -r requirements-dev.txt
  - python3 -m pip install --upgrade -r requirements.txt
  - python3 -m flake8 etw

script:
  - python3 setup.py test

deploy:
  - provider: pypi
    distributions: bdist_wheel
    on:
      tags: true
    user: jegm # pypi user name
    password:
      secure: encrypted-password
